### ISSUE TITLE
ValueError when trying freeze_graph.py

### ISSUE THREAD

**Issue by WiiliamC** [GuiUzeda/tf-graph-freeze#1]
Hi
I'm trying to freeze my model but when I run freeze_graph.py, something comes out like this
`Traceback (most recent call last):
  File "freeze_graph.py", line 105, in <module>
    main(args)
  File "freeze_graph.py", line 64, in main
    tf.import_graph_def(output_graph_def, name="")
  File "/home/chan/.local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/chan/.local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 430, in import_graph_def
    raise ValueError(str(e))
ValueError: Input 0 of node final_training_ops/Variable/Assign was passed float from final_training_ops/Variable:0 incompatible with expected float_ref.
`
Do you know how to fix it?
Thanks

**Comment by GuiUzeda** [comment]
Hi,

It seems something to do with the nodes that you want to keep

How did you called the function?
Did you specify all the nodes you want to keep in a pickled file?
